server:
  port: ${AUTH_SERVICE_PORT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    registry-fetch-interval-seconds: 1
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
spring:
  application:
    name: auth-service
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: bank-realm
  client-id: auth-service
  client-secret: ${AUTH_SERVICE_KEYCLOAK_SECRET}
management:
  server:
    port: 8081
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs
  api-path-segment: auth